[package]
name = "compiler"
version = "0.1.0"
edition = "2021"
authors = ["Anthony Rubick"]

[[bin]]
name = "scanner"
path = "src/bins/scanner.rs"


[dependencies]

[dev-dependencies]
pretty_assertions = "1.4"
rstest = "0.24"
