mod automaton;
mod binrep;
mod branch;
mod error_string;
mod expression;
mod fibonacci;
mod formulae;
mod funcall;
mod funcall2;
mod illegal;
mod loop_;
mod mandel;
mod max;
mod parameter;
mod parse;
mod parse2;
mod polymorphism;
mod recursion;
mod sort;
mod square;
mod tax;
mod times8;
mod trivial;
mod validate_program_outputs;

pub use compiler::bin_utils::{run_scanner, scan};
